(cl:defpackage model_server-srv
  (:use )
  (:export
   "IMAGEREQUEST"
   "<IMAGEREQUEST-REQUEST>"
   "IMAGEREQUEST-REQUEST"
   "<IMAGEREQUEST-RESPONSE>"
   "IMAGEREQUEST-RESPONSE"
   "MODELREQUEST"
   "<MODELREQUEST-REQUEST>"
   "MODELREQUEST-REQUEST"
   "<MODELREQUEST-RESPONSE>"
   "MODELREQUEST-RESPONSE"
  ))

