// Generated by gencpp from file model_server/ImageRequest.msg
// DO NOT EDIT!


#ifndef MODEL_SERVER_MESSAGE_IMAGEREQUEST_H
#define MODEL_SERVER_MESSAGE_IMAGEREQUEST_H

#include <ros/service_traits.h>


#include <model_server/ImageRequestRequest.h>
#include <model_server/ImageRequestResponse.h>


namespace model_server
{

struct ImageRequest
{

typedef ImageRequestRequest Request;
typedef ImageRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageRequest
} // namespace model_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::model_server::ImageRequest > {
  static const char* value()
  {
    return "fba05cbe092f5fd7d13b6a12503ed6ac";
  }

  static const char* value(const ::model_server::ImageRequest&) { return value(); }
};

template<>
struct DataType< ::model_server::ImageRequest > {
  static const char* value()
  {
    return "model_server/ImageRequest";
  }

  static const char* value(const ::model_server::ImageRequest&) { return value(); }
};


// service_traits::MD5Sum< ::model_server::ImageRequestRequest> should match
// service_traits::MD5Sum< ::model_server::ImageRequest >
template<>
struct MD5Sum< ::model_server::ImageRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::model_server::ImageRequest >::value();
  }
  static const char* value(const ::model_server::ImageRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::model_server::ImageRequestRequest> should match
// service_traits::DataType< ::model_server::ImageRequest >
template<>
struct DataType< ::model_server::ImageRequestRequest>
{
  static const char* value()
  {
    return DataType< ::model_server::ImageRequest >::value();
  }
  static const char* value(const ::model_server::ImageRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::model_server::ImageRequestResponse> should match
// service_traits::MD5Sum< ::model_server::ImageRequest >
template<>
struct MD5Sum< ::model_server::ImageRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::model_server::ImageRequest >::value();
  }
  static const char* value(const ::model_server::ImageRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::model_server::ImageRequestResponse> should match
// service_traits::DataType< ::model_server::ImageRequest >
template<>
struct DataType< ::model_server::ImageRequestResponse>
{
  static const char* value()
  {
    return DataType< ::model_server::ImageRequest >::value();
  }
  static const char* value(const ::model_server::ImageRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODEL_SERVER_MESSAGE_IMAGEREQUEST_H
