// Generated by gencpp from file model_server/ModelRequestRequest.msg
// DO NOT EDIT!


#ifndef MODEL_SERVER_MESSAGE_MODELREQUESTREQUEST_H
#define MODEL_SERVER_MESSAGE_MODELREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace model_server
{
template <class ContainerAllocator>
struct ModelRequestRequest_
{
  typedef ModelRequestRequest_<ContainerAllocator> Type;

  ModelRequestRequest_()
    : model()  {
    }
  ModelRequestRequest_(const ContainerAllocator& _alloc)
    : model(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _model_type;
  _model_type model;





  typedef boost::shared_ptr< ::model_server::ModelRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::model_server::ModelRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModelRequestRequest_

typedef ::model_server::ModelRequestRequest_<std::allocator<void> > ModelRequestRequest;

typedef boost::shared_ptr< ::model_server::ModelRequestRequest > ModelRequestRequestPtr;
typedef boost::shared_ptr< ::model_server::ModelRequestRequest const> ModelRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::model_server::ModelRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::model_server::ModelRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::model_server::ModelRequestRequest_<ContainerAllocator1> & lhs, const ::model_server::ModelRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model == rhs.model;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::model_server::ModelRequestRequest_<ContainerAllocator1> & lhs, const ::model_server::ModelRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace model_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::model_server::ModelRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::model_server::ModelRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::model_server::ModelRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::model_server::ModelRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::model_server::ModelRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::model_server::ModelRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::model_server::ModelRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f3dcb935694565eda084843802a1ee4";
  }

  static const char* value(const ::model_server::ModelRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f3dcb935694565eULL;
  static const uint64_t static_value2 = 0xda084843802a1ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::model_server::ModelRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "model_server/ModelRequestRequest";
  }

  static const char* value(const ::model_server::ModelRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::model_server::ModelRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String model\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::model_server::ModelRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::model_server::ModelRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModelRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::model_server::ModelRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::model_server::ModelRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "model: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODEL_SERVER_MESSAGE_MODELREQUESTREQUEST_H
