// Generated by gencpp from file model_server/ModelRequest.msg
// DO NOT EDIT!


#ifndef MODEL_SERVER_MESSAGE_MODELREQUEST_H
#define MODEL_SERVER_MESSAGE_MODELREQUEST_H

#include <ros/service_traits.h>


#include <model_server/ModelRequestRequest.h>
#include <model_server/ModelRequestResponse.h>


namespace model_server
{

struct ModelRequest
{

typedef ModelRequestRequest Request;
typedef ModelRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModelRequest
} // namespace model_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::model_server::ModelRequest > {
  static const char* value()
  {
    return "84e67d26165d3d65758a56814ed143ba";
  }

  static const char* value(const ::model_server::ModelRequest&) { return value(); }
};

template<>
struct DataType< ::model_server::ModelRequest > {
  static const char* value()
  {
    return "model_server/ModelRequest";
  }

  static const char* value(const ::model_server::ModelRequest&) { return value(); }
};


// service_traits::MD5Sum< ::model_server::ModelRequestRequest> should match
// service_traits::MD5Sum< ::model_server::ModelRequest >
template<>
struct MD5Sum< ::model_server::ModelRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::model_server::ModelRequest >::value();
  }
  static const char* value(const ::model_server::ModelRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::model_server::ModelRequestRequest> should match
// service_traits::DataType< ::model_server::ModelRequest >
template<>
struct DataType< ::model_server::ModelRequestRequest>
{
  static const char* value()
  {
    return DataType< ::model_server::ModelRequest >::value();
  }
  static const char* value(const ::model_server::ModelRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::model_server::ModelRequestResponse> should match
// service_traits::MD5Sum< ::model_server::ModelRequest >
template<>
struct MD5Sum< ::model_server::ModelRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::model_server::ModelRequest >::value();
  }
  static const char* value(const ::model_server::ModelRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::model_server::ModelRequestResponse> should match
// service_traits::DataType< ::model_server::ModelRequest >
template<>
struct DataType< ::model_server::ModelRequestResponse>
{
  static const char* value()
  {
    return DataType< ::model_server::ModelRequest >::value();
  }
  static const char* value(const ::model_server::ModelRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODEL_SERVER_MESSAGE_MODELREQUEST_H
